/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.adpl.kedaikopigui.event;

/**
 *
 * @author faizd
 */
public class ChekBoxTambahan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChekBoxTambahan.class.getName());

    /**
     * Creates new form ChekBoxTambahan
     */
    public ChekBoxTambahan() {
        initComponents();
    }
    
    private String formatRupiah(int nominal){
        return "Rp " + String.format(java.util.Locale.forLanguageTag("id-ID"), "%,d", nominal);
    }
    
    private void hitungTotal(){
        int total = 25000;
        
        if(cbGulaAren.isSelected()) total += 3000;
        if(cbSusuOat.isSelected()) total += 5000;
        if(cbExtraShot.isSelected()) total += 4000;
        
        lbTotal.setText(formatRupiah(total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbGulaAren = new javax.swing.JCheckBox();
        cbSusuOat = new javax.swing.JCheckBox();
        cbExtraShot = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tambahan Kopi");

        jLabel1.setText("Tambahan:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Latte - Rp 25.000");

        cbGulaAren.setText("Gula Aren (+ Rp 3.000)");
        cbGulaAren.addActionListener(this::cbGulaArenActionPerformed);

        cbSusuOat.setText("Susu Oat (+ Rp 5.000)");
        cbSusuOat.addActionListener(this::cbSusuOatActionPerformed);

        cbExtraShot.setText("Extra Shot (+ Rp 4.000)");
        cbExtraShot.addActionListener(this::cbExtraShotActionPerformed);

        jLabel3.setText("Total: ");

        lbTotal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTotal.setText("Rp 25.000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(cbGulaAren)
                    .addComponent(cbSusuOat)
                    .addComponent(cbExtraShot)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotal)))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbGulaAren)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSusuOat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbExtraShot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbTotal))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbGulaArenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGulaArenActionPerformed
        // TODO add your handling code here:
        hitungTotal();
    }//GEN-LAST:event_cbGulaArenActionPerformed

    private void cbSusuOatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSusuOatActionPerformed
        // TODO add your handling code here:
        hitungTotal();
    }//GEN-LAST:event_cbSusuOatActionPerformed

    private void cbExtraShotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbExtraShotActionPerformed
        // TODO add your handling code here:
        hitungTotal();
    }//GEN-LAST:event_cbExtraShotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ChekBoxTambahan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbExtraShot;
    private javax.swing.JCheckBox cbGulaAren;
    private javax.swing.JCheckBox cbSusuOat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbTotal;
    // End of variables declaration//GEN-END:variables
}
