/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.adpl.kedaikopigui.layout;

/**
 *
 * @author faizd
 */
public class BorderLayoutMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BorderLayoutMenu.class.getName());

    /**
     * Creates new form BorderLayoutMenu
     */
    public BorderLayoutMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbJudul = new javax.swing.JLabel();
        lbNamaKopi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        lbHarga = new javax.swing.JLabel();
        lbJamBuka = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Kopi");
        getContentPane().setLayout(new java.awt.BorderLayout(6, 6));

        lbJudul.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbJudul.setText("Kopi Pilihan Hari ini");
        getContentPane().add(lbJudul, java.awt.BorderLayout.PAGE_START);

        lbNamaKopi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNamaKopi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNamaKopi.setText("Americano");
        lbNamaKopi.setPreferredSize(new java.awt.Dimension(110, 20));
        getContentPane().add(lbNamaKopi, java.awt.BorderLayout.LINE_START);

        txtDeskripsi.setEditable(false);
        txtDeskripsi.setColumns(20);
        txtDeskripsi.setLineWrap(true);
        txtDeskripsi.setRows(5);
        txtDeskripsi.setText("Ini ada Kopi Hitam khas Aceh");
        txtDeskripsi.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDeskripsi);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        lbHarga.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lbHarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHarga.setText("Rp 20.000");
        lbHarga.setPreferredSize(new java.awt.Dimension(110, 21));
        getContentPane().add(lbHarga, java.awt.BorderLayout.LINE_END);

        lbJamBuka.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbJamBuka.setText("Buka Setiap Hari 08:00 - 23:00");
        getContentPane().add(lbJamBuka, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BorderLayoutMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbHarga;
    private javax.swing.JLabel lbJamBuka;
    private javax.swing.JLabel lbJudul;
    private javax.swing.JLabel lbNamaKopi;
    private javax.swing.JTextArea txtDeskripsi;
    // End of variables declaration//GEN-END:variables
}
