/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.adpl.kedaikopigui.layout;

/**
 *
 * @author faizd
 */
public class FlowLayoutTambahan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FlowLayoutTambahan.class.getName());

    /**
     * Creates new form FlowLayoutTambahan
     */
    public FlowLayoutTambahan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTambahan = new javax.swing.JLabel();
        btnSusuOat = new javax.swing.JButton();
        btnExtraShot = new javax.swing.JButton();
        btnEsBatu = new javax.swing.JButton();
        btnSirupCaramel = new javax.swing.JButton();
        btnSirupVanilla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 6, 6));

        lbTambahan.setText("Pilih Tambahan: ");
        getContentPane().add(lbTambahan);

        btnSusuOat.setText("Susu Oat");
        getContentPane().add(btnSusuOat);

        btnExtraShot.setText("Extra Shot");
        getContentPane().add(btnExtraShot);

        btnEsBatu.setText("Es Batu");
        getContentPane().add(btnEsBatu);

        btnSirupCaramel.setText("Sirup Caramel");
        getContentPane().add(btnSirupCaramel);

        btnSirupVanilla.setText("Sirup Vanilla");
        getContentPane().add(btnSirupVanilla);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FlowLayoutTambahan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEsBatu;
    private javax.swing.JButton btnExtraShot;
    private javax.swing.JButton btnSirupCaramel;
    private javax.swing.JButton btnSirupVanilla;
    private javax.swing.JButton btnSusuOat;
    private javax.swing.JLabel lbTambahan;
    // End of variables declaration//GEN-END:variables
}
